---
- name: Elk_Playbook.yml
  hosts: elk
  become: true
  tasks:


  - name: sysctl confg
    sysctl:
        name: vm.max_map_count
        sysctl_set : yes
        value: '262144'
        reload: yes

  - name: Install docker.io via apt
    apt:
       update_cache: yes
       name: docker.io
       state: present

  - name: Install python3-pip via apt
    apt:
       name: python3-pip
       state: present

  - name: Install docker via pip
    pip:
       name: docker
       state: present

  - name: install the container sebp/elk:761
    docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

  - name: make sure docker service is started when VM restarts
    systemd:
       name: docker
       enabled: yes
